version: "3"
services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
      - "1400-1500:1400-1500"
    volumes:
      - ./contents/:/var/www
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./sites/:/etc/nginx/conf.d/
      - ./logs/:/var/log/nginx/
      - ./certs/:/etc/nginx/certs/
    networks:
      - mongo
networks:
  mongo:
    external: true
